<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP78gpkp\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP78gpkp/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerP78gpkp.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerP78gpkp\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerP78gpkp\appProdProjectContainer(array(
    'container.build_hash' => 'P78gpkp',
    'container.build_id' => '8be5ca0f',
    'container.build_time' => 1533498511,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerP78gpkp');
